# Python Numpy Tutorial

## 1. Python

### i. Quicksort Algorithm

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) / 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print quicksort([3,6,8,10,1,2,1])

[1, 1, 2, 3, 6, 8, 10]


### ii. Basic data types

#### Numbers

In [6]:
x = 3
print type(x)
print x
print x + 1
print x - 1
print x * 2
print x**2
x += 1
print x
x *= 2
print x
y = 2.5
print type(y)
print y, y+1, y*2, y**2

<type 'int'>
3
4
2
6
9
4
8
<type 'float'>
2.5 3.5 5.0 6.25


#### Booleans

In [7]:
t = True
f = False
print type(t)
print t and f
print t or f
print not t
print t != f

<type 'bool'>
False
True
False
True


#### Strings

In [8]:
hello = 'hello'
world = "world"
print hello
print len(hello)
hw = hello + ' ' + world
print hw
hw12 = '%s %s %d' % (hello, world, 12)
print hw12

hello
5
hello world
hello world 12


In [9]:
s= "hello"
print s.capitalize()
print s.upper()
print s.rjust(7)
print s.center(7)
print s.replace('l','(ell)')
print '  world '.strip()

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### iii. Containers

#### Lists

In [10]:
xs = [3, 1, 2]
print xs, xs[2]
print xs[-1]
xs[2] = 'foo'
print xs
xs.append('bar')
print xs
x = xs.pop()
print x, xs

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [12]:
# Slicing
nums = range(5)
print nums
print nums[2:4]
print nums[2:]
print nums[:2]
print nums[:]
print nums[:-1]
nums[2:4] = [8,9]
print nums

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [13]:
# Loops
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print animal

cat
dog
monkey


In [15]:
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

#1: cat
#2: dog
#3: monkey


In [17]:
# List comprehensions
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x**2)
print squares

[0, 1, 4, 9, 16]


In [19]:
squares = [x**2 for x in nums]
print squares

[0, 1, 4, 9, 16]


In [21]:
even_squares = [x for x in squares if x % 2 == 0]
print even_squares

[0, 4, 16]


In [22]:
even_squares = [x**2 for x in nums if x % 2 == 0]
print even_squares

[0, 4, 16]


#### Dictionaries

In [25]:
d = {'cat':'cute', 'dog':'furry'}
print d['cat']
print 'cat' in d
d['fish'] = 'wet'
print d['fish']
#print d['monkey']
print d.get('monkey', 'N/A')
print d.get('fish', 'N/A')
del d['fish']
print d.get('fish', 'N/A')

cute
True
wet
N/A
wet
N/A


In [2]:
# Loops
d = {'person':2, 'cat':4, 'spider':8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [3]:
for animal, legs in d.iteritems():
    print 'A %s has %d legs' % (animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [5]:
# Dictionary Comprehensions
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x:x**2 for x in nums if x %2 == 0}
print even_num_to_square

{0: 0, 2: 4, 4: 16}


#### Sets

In [8]:
animals = {'cat', 'dog'}
print 'cat' in animals
print 'fish' in animals
animals.add('fish')
print 'fish' in animals
print len(animals)
animals.add('cat')
print len(animals)
animals.remove('cat')
print len(animals)

True
False
True
3
3
2


In [9]:
# Loops
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

#1: fish
#2: dog
#3: cat


In [15]:
# Set comprehensions
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print nums

set([0, 1, 2, 3, 4, 5])


#### Tuples

In [18]:
d = {(x, x + 1):x for x in range(10)} #Create a dictionary with tuples as keys
print d
t = (5,6) 
print type(t)
print d[t]
print d[(1,2)]

{(0, 1): 0, (1, 2): 1, (6, 7): 6, (5, 6): 5, (7, 8): 7, (8, 9): 8, (4, 5): 4, (2, 3): 2, (9, 10): 9, (3, 4): 3}
<type 'tuple'>
5
1


### iv. Functions

In [22]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x == 0:
        return 'zero'
    else:
        return 'negative'

for x in [-1, 0 , 1]:
    print sign(x)

negative
zero
positive


In [24]:
def hello(name, loud = False):
    if loud:
        print 'HELLO, %s!' % (name.upper())
    else:
        print 'hello, %s' % (name)
        
hello('bob')
hello('Fred', loud = True)

hello, bob
HELLO, FRED!


### v. Classes

In [25]:
class Greeter(object):
    
    # Constructor
    def __init__(self, name):
        self.name = name # Create an instance variable
        
    # Instance Method
    def greet(self, loud = False):
        if loud:
            print 'HELLO, %s!' % self.name.upper()
        else:
            print 'hello, %s' % self.name
            
g = Greeter('Fred') # Construct an instance of the Greeter class
g.greet() # Call an instance method
g.greet(loud = True)            

hello, Fred
HELLO, FRED!


## 2. Numpy

### i. Arrays

In [34]:
import numpy as np

a = np.array([1,2,3])
print type(a)
print a.shape
print a[0], a[1], a[2]
a[0] = 5
print a

b = np.array([[1,2,3],[4,5,6]])
print b.shape
print b[0,0], b[0,1], b[1,0]

<type 'numpy.ndarray'>
(3L,)
1 2 3
[5 2 3]
(2L, 3L)
1 2 4


In [38]:
a = np.zeros((2,2))
print a

b = np.ones((1,2))
print b

c = np.full((2,2), 7)
print c

d = np.eye(2)
print d

e = np.random.random((2,2))
print e

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.32322905  0.50655896]
 [ 0.00790191  0.67819509]]


C:\Anaconda\lib\site-packages\numpy\core\numeric.py:294: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


### ii. Array Indexing

#### Slicing

In [48]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print a
b = a[:2,1:3]
print b

print a[0,1]
b[0,0] = 77
print a[0,1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [49]:
row_r1 = a[1,:] #Results in a rank 1 view
row_r2 = a[1:2,:] #Results in a rank 2 view
print row_r1, row_r1.shape
print row_r2, row_r2.shape

col_r1 = a[:,1] #Rank 1
col_r2 = a[:,1:2] #Rank 2
print col_r1, col_r1.shape
print col_r2, col_r2.shape

[5 6 7 8] (4L,)
[[5 6 7 8]] (1L, 4L)
[77  6 10] (3L,)
[[77]
 [ 6]
 [10]] (3L, 1L)


#### Integer Array Indexing

In [50]:
a = np.array([[1,2],[3,4],[5,6]])

print a[[0,1,2],[0,1,0]]
print np.array([a[0,0],a[1,1],a[2,0]])

print a[[0,0],[1,1]]
print np.array([a[0,1],a[0,1]])

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print a
b = np.array([0,2,0,1])
print a[np.arange(4), b]

a[np.arange(4), b] += 10
print a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Boolean Array Indexing

In [54]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
print bool_idx
print a[bool_idx]

print a[a > 2]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### iii. Datatypes

In [56]:
x = np.array([1,2])
print x.dtype

x = np.array([1.0,2.0])
print x.dtype

x = np.array([1,2], dtype = np.int64)
print x.dtype

int32
float64
int64


### iv. Array Math

In [58]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

#Element-wise sum
print x + y
print np.add(x, y)

#Element-wise difference
print x - y
print np.subtract(x, y)

#Element-wise product
print x * y
print np.multiply(x, y)

#Element-wise division
print x / y
print np.divide(x, y)

#Element-wise square-root
print np.sqrt(x)

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [59]:
v = np.array([9, 10])
w = np.array([11,12])

#Inner product of vectors
print v.dot(w)
print np.dot(v,w)
print np.dot(w,v)

#Matrix vector product
print x.dot(v)
print np.dot(x,v)
print np.dot(v,x)

#Matrix matrix product
print x.dot(y)
print np.dot(x,y)
print y.dot(x)

219
219
219
[ 29.  67.]
[ 29.  67.]
[ 39.  58.]
[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]
[[ 23.  34.]
 [ 31.  46.]]


In [62]:
print np.sum(x)
print np.sum(x, axis = 0) # Along columns
print np.sum(x, axis = 1) # Along rows

10.0
[ 4.  6.]
[ 3.  7.]


In [65]:
print x
print x.T #Transpose

v = np.array([1,2,3])
print v
print v.T #Does nothing

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[1 2 3]
[1 2 3]


### v. Broadcasting

In [73]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

print y

for i in range(4):
    y[i,:] = x[i,:] + v
    
print y

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [76]:
# Above can be made more efficient by stacking vector v so that it's the same size as x, and then performing elementwise
# addtion. This is more efficient on larger arrays because we can avoid the for loop

vv = np.tile(v, (4,1)) #Stack 4 copies of v on top of each other
print vv

y = x + vv
print y

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [77]:
# In actuality, we don't even need to stack the vector v. Broadcasting does that automatically for us.

y = x + v
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [78]:
# Applications of broadcasting
v = np.array([1,2,3])
w = np.array([4,5])

print np.reshape(v, (3,1)) * w

x = np.array([[1,2,3],[4,5,6]])
print x + v

print (x.T + w).T
print x + np.reshape(w, (2,1))

print x * 2

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## 3. SciPy